---
title: "LinHac"
author: "Xikai wu"
date: "2024-04-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(ggplot2)
```

```{r}
df=read.csv("Linhac24_Sportlogiq.csv")
```

```{r}
df_pass_between_shots=df %>% group_by(gameid) %>%
  mutate(current_shot=cumsum(eventname=="shot"))%>%
  #filter(eventname=="pass")#%>%
  #group_by(gameid,current_shot)%>%
  filter(eventname=="pass")%>%
  add_count(gameid,current_shot,name="pass_between")
df_pass_by_team=df%>% group_by(gameid)%>%
  mutate(current_shot=cumsum(eventname=="shot"))%>%
  filter(eventname=="pass")%>%
  add_count(gameid,current_shot,teamid,name="pass_between")
df_joined_passbetween=left_join(df,df_pass_between_shots)
```

```{r}
teams=unique(df$teamid)
#for (i in teams){
#  df_pass_by_team%>%filter(teamid==i)%>%group_by(gameid,current_shot)
#}
temp=df_pass_by_team%>%filter(teamid==814)%>%group_by(gameid,current_shot)%>%summarize(pass_count=pass_between[1],teamid=teamid[1])



## Try to figure out passes leading up to a shot
df_possession_id=df%>%filter(!is.na(teaminpossession))%>%#group_by(gameid)%>% add group by gameid for per game
  mutate(possession_id=cumsum(c(1, diff(teaminpossession) != 0)))
## if a possession contain a shot attempt, then count number of passes within the posession that leads up to the shot
containShot=function(event){
  has_shot=(event=="shot")
  if (sum(has_shot)>0){
    return(rep(TRUE,length(event)))
  }
  else{
    return(rep(FALSE,length(event)))
  }
}
posession_with_shot=df_possession_id%>%group_by(possession_id)%>%reframe(has_shot=containShot(eventname))
df_possession_id$has_shot=posession_with_shot$has_shot
##now i have df with posession column and filter by whether the possession contains a shot
## then we could groupby possession then count the pass between each shot.
df_pass_betweenshot_per_possession=df_possession_id%>%filter(has_shot==T)%>%group_by(possession_id)%>%mutate(pass_count=cumsum(eventname=="pass"),time_since_possession=compiledgametime-compiledgametime[1])%>%filter(eventname=="shot")%>%mutate(passes_between_shots = pass_count - lag(pass_count, default =0),time_since_shot=time_since_possession-lag(time_since_possession,default=0))
df_pass_shot_clean=df_pass_betweenshot_per_possession%>%select(gameid,teaminpossession,possession_id,eventname,outcome,pass_count,passes_between_shots,time_since_possession,time_since_shot)
```
